apiVersion: v1
kind: Service
metadata:
  name: fastapi-docker-example
  labels:
    app: fastapi-docker-example
spec:
  type: NodePort
  selector:
    app: fastapi-docker-example
  ports:
  - port: 80
    targetPort: 8000
